Repository inthepocket/hubble-scripts, pull requests merged in 2019-06, with the labels that each got.

#36 Export extra scales 1.5x and 4x for Android
  sketchtool.sh
Labels: enhancement

#37 3.5.0
  .github/ISSUE_TEMPLATE.md
  LICENSE
  README.md
  __mocks__/sample_dump.json
  __mocks__/sample_output.document.json
  __mocks__/sample_output.json
  __mocks__/sample_sketchfile.sketch
  __tests__/__snapshots__/verifyMocks.test.js.snap
  sketchtool.sh
Labels: release 🔖

#39 Correctly map the 1.5x scale
  package.json
  sketchtool.sh
Labels: bug

#40 hubble-cli@3.4.1
  package.json
  sketchtool.sh
Labels: release 🔖

#38 Restructure style dictionary tokens, add extra mappings
  __mocks__/sample_output.document.json
  __mocks__/sample_output.json
  __mocks__/sample_output.styledictionary.json
  __tests__/__snapshots__/verifyMocks.test.js.snap
  lib/__tests__/styleDictionary.test.js
  lib/font.js
  lib/mappers/__tests__/__snapshots__/mapper.test.js.snap
  lib/mappers/textstyle.js
  lib/styleDictionary/assetMapping.js
  lib/styleDictionary/colorMapping.js
  lib/styleDictionary/fontMapping.js
  lib/styleDictionary/index.js
  lib/styleDictionary/sizeMapping.js
  lib/styleDictionary/util.js
  lib/styleDictionary/weightMapping.js
Labels: enhancement

#42 Add line height support back in
  __mocks__/sample_output.styledictionary.json
  __tests__/__snapshots__/verifyMocks.test.js.snap
  lib/styleDictionary/index.js
  lib/styleDictionary/lineHeightMapping.js
Labels: enhancement
